apiVersion: v1
kind: Service
metadata:
  name: webapp-blue
  labels:
    app: webapp
    version: blue
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: webapp
    version: blue 