apiVersion: v1
kind: Service
metadata:
  name: webapp-green
  labels:
    app: webapp
    version: green
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: webapp
    version: green 