apiVersion: v1
kind: Service
metadata:
  name: webapp-router
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    app: webapp
    # Изначально маршрутизируем на blue-версию
    version: blue 