apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: webapp
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "postgres"
  APP_VERSION: "1.0.0" 